### ISSUE TITLE
Collaboration opportunitiees

### ISSUE THREAD

**Issue by quocdat32461997** [SoYoungCho/Knowledge-Structure-Similarity-Measure#1]
Hi Soyoung, 
I would like to Colab w/ u on this project. This project lies between NLP and Knowledge Discovery which attracts me. I wonder if I have a chance to work soon this. Pretty much, I want to make it as a research project. Thanks.

**Comment by quocdat32461997** [comment]
I hope my request is not too aggressive. Forgive me for any inconvenience.

**Comment by SoYoungCho** [comment]
Hi 😉

Thank you for your interest and offer in this project. 🤩
Actually, I have developed this similarity measure between two weighted knowledge graphs where the node is keyword and edge is the relation with similarity scores. However, I am afraid it is not possible to develop this as a collaboration project since this work was based on our lab's private knowledge structure generating system. 😂😂
Still, I am happy to share some ideas on this work using NLP algorithms as this work at my lab was done with traditional text-mining algorithms. If you are interested, please contact soyoung.cho@kaist.ac.kr.

Thanks
Stay safe!

**Comment by quocdat32461997** [comment]
Thanks.
